using System;
using UnityEngine;

/// <summary>
///     A class that provides a common interface for reading the data for randomly generated
///     dungeons and dungeons loaded from a file.
/// </summary>
class DungeonLayoutGenerator
{
    // ---------------------------------------------------------------------------------------------
    // FILE
    // ---------------------------------------------------------------------------------------------
    /// <summary>
    ///     The dungeon tile info that was read when loading a dungeon layout.
    /// </summary>
    private readonly DungeonTileStruct[] fileTiles;
    /// <summary>
    ///     Indicates if the dungeon was generated by loading a layout file.
    /// </summary>
    private readonly bool fromFile;
    
    // ---------------------------------------------------------------------------------------------
    // INFORMATION
    // ---------------------------------------------------------------------------------------------
    /// <summary>
    ///     Equals the product of each of the layout dimensions.
    /// </summary>
    public readonly int tileCount;
    /// <summary>
    ///     The x, y, z dimensions of the dungeon layout to generate.
    /// </summary>
    public readonly Vector3Int layoutDimensions;
    /// <summary>
    ///     The index of the dungeon's origin.
    /// </summary>
    public readonly Vector3Int rootPosition;
    /// <summary>
    ///     The connectivity information for each dungeon tile.
    /// </summary>
    private readonly LatticeGraph lattice;
    /// <summary>
    ///     The dungeon that this generator was created by.
    /// </summary>
    private Dungeon parentDungeon;

    /// <summary>
    ///     Randomly generate a dungeon of the specified size, rooted at the specified position.
    /// </summary>
    /// <param name="layoutDimensions">
    ///     The dimensions of the dungeon to generate.
    /// </param>
    /// <param name="rootPosition">
    ///     The position of the root of the dungeon.
    /// </param>
    public DungeonLayoutGenerator(Vector3Int layoutDimensions, Vector3Int rootPosition, Dungeon parentDungeon)
    {
        this.layoutDimensions = layoutDimensions;
        this.rootPosition = rootPosition;

        lattice = new(layoutDimensions, rootPosition);

        tileCount = layoutDimensions.x * layoutDimensions.y * layoutDimensions.z;
        fromFile = false;
        this.parentDungeon = parentDungeon;
    }

    /// <summary>
    ///     Generate the dungeon specified by the given file.
    /// </summary>
    /// <param name="layoutFile">
    ///     The layout file to parse.
    /// </param>
    public DungeonLayoutGenerator(TextAsset layoutFile, Dungeon parentDungeon)
    {
        DungeonLayoutStruct layoutStruct = JsonUtility.FromJson<DungeonLayoutStruct>(layoutFile.text);

        layoutDimensions = layoutStruct.layoutDimensions;
        rootPosition = layoutStruct.rootPosition;

        fileTiles = layoutStruct.layout;

        tileCount = fileTiles.Length;
        fromFile = true;
        this.parentDungeon = parentDungeon;
        parentDungeon.gameObject.name = layoutStruct.dungeonName;
    }

    /// <param name="position">
    ///     The position of the tile to get.
    /// </param>
    /// <returns>
    ///     The tile at the specified position.
    /// </returns>
    public DungeonTile GetTile(int index, Vector3Int position)
    {
        string tileName;
        DungeonTileType tileType;
        Quaternion tileRotation;

        if (fromFile)
        {
            (tileName, tileType, tileRotation) = GetTileFromFile(index);
        }
        else
        {
            (tileName, tileType, tileRotation) = GetTileFromLattice(position);
        }
        
        DungeonTile tile = DungeonTile.MakeTile(
            parentDungeon.name + "-" + tileName + "-" + string.Join("_", position),
            tileType, position, tileRotation, parentDungeon
        );

        return tile;
    }

    /// <param name="position">
    ///     The position of the tile to get.
    /// </param>
    /// <returns>
    ///     The tile from the layout file lines, at the specified position.
    /// </returns>
    private (string, DungeonTileType, Quaternion) GetTileFromFile(int index)
    {
        string tileName = fileTiles[index].tileName;
        string tileOrientation = fileTiles[index].tileOrientation;

        Enum.TryParse(tileName, true, out DungeonTileType tileType);
        return (tileName, tileType, Rotation.Parse(tileOrientation));
    }
    
    /// <param name="position">
    ///     The position of the tile to get.
    /// </param>
    /// <returns>
    ///     The tile from the randomly generated layout, at the specified position.
    /// </returns>
    private (string, DungeonTileType, Quaternion) GetTileFromLattice(Vector3Int position)
    {
        (DungeonTileType tileType, Quaternion tileRotation) = lattice[position].TileInfo();

        return (tileType.GetName(), tileType, tileRotation);
    }

    /// <param name="position">
    ///     The position of the tile to check.
    /// </param>
    /// <returns>
    ///     <tt>True</tt> iff the tile at the specified position is empty.
    /// </returns>
    public bool IsEmpty(int index, Vector3Int position)
    {
        if (fromFile)
        {
            return fileTiles[index].tileName == "empty";
        }
        else
        {
            return !lattice.IsSet(position);
        }
    }
}